---
title: "About this website"
number-sections: false
---

-----

<hr style="height:1pt; visibility:hidden;" />

*This is the website for the hands-on "R for Reproducibility" workshop taught at*
*Ohio State University on August 18^th^, 2025.*

### Practical information about the workshop

R is a programming language that is especially powerful for data exploration,
visualization, and statistical analysis. 
During this workshop, participants will learn the basics of R and RStudio,
and how to use R for reproducible data manipulation and visualization.

If you are affiliated with Ohio State University in any capacity,
you can attend this workshop for free by
[registering here](https://library.osu.edu/events/r-for-scientific-reproducibility). You can find some more information about the workshop [here](https://imageomics.github.io/2026-02-09-osu-online/).

There are no prerequisites: this workshop is suitable for complete beginners
in R and in coding in general.
This workshop is taught online via Zoom.

### Instructors and organizers

This workshop is taught by the organizers of [OSU Code Club](https://osu-codeclub.github.io):

- **Horacio Lopez-Nicora** [{{< fa envelope >}}](mailto:lopez-nicora.1@osu.edu) --
  Assistant Professor in the department of [Plant Pathology](https://plantpath.osu.edu)

- **Jelmer Poelstra** [{{< fa envelope >}}](mailto:poelstra.1@osu.edu) --
  Bioinformatics & Microscopy Lead at the CFAES
  [Molecular and Cellular Imaging Center (MCIC)](https://mcic.osu.edu)

- **Jessica Cooperstone** [{{< fa envelope >}}](mailto:cooperstone.1@osu.edu) --
  Associate Professor in the departments of
  [Horticulture & Crop Science](https://hcs.osu.edu),
  and [Food Science & Technology](https://fst.osu.edu)

The following **helpers** will be assisting participants:

- Hannah Toth
- Menuka Bhandari
- Kelsey Badger
- Matthew Thompson
- Elizabeth Campolongo
- Net Zhang
- Jay

This workshop is organized by **Kelsey Badger** at the
[OSU Research Commons](https://library.osu.edu/researchcommons), and
Matthew Thompson and Elizabeth Campolongo at the
[OSU Imageomics Institute](https://imageomics.osu.edu/).

### The Carpentries

**This is a [Carpentries](https://carpentries.org/) workshop.**
The Carpentries project comprises the Software Carpentry, Data Carpentry,
and Library Carpentry communities of Instructors, Trainers, Maintainers, helpers,
and supporters who share a mission to teach foundational computational and
data science skills to researchers.

The material on this website has been adapted from the
[R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/)
Software Carpentry lesson.

A [sister workshop](https://library.osu.edu/events/version-control-with-git)
is being held on February 9^th^ on version control with Git and GitHub.
